### ISSUE TITLE
webinterface "updater"

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#203]
**Webinterface "Updater"**

**Page Description**
The Updater provides an overview screen of all installed components.
The components are matched against our registry and their version is compared to the latest version in the registry. If the version in the registry is higher, than the installed one, an update link is provided.
Update Link (action) fetches the download archive, extracts it and installs the files in the correct folders.

**Webinterface Link**
http://localhost/tools/webinterface/index.php?page=update

**Todo List**
- [x] check for installed components
- [x] detect versions
- [x] ask wpn-xm server for registry
- [x] compare installed version against latest registry version
  - [ ] either by service request
  - [x] or checking agaisnt downloaded registry
- [x] show new version number and provide update button ("update to v1.2.3")
- [x] update action for individual component "update&component=xy"
- [ ] download & unzip
  - [ ] class Downloader  
- [ ] make it do the update thing
  - [ ] add install() methods to Component classes

**Comment by jakoch** [comment]
We don't need downloading on two sides: webinterface and server control panel.
That's why the updater will be removed, in favor of downloading through the server control panel.
Closing.
