### ISSUE TITLE
renaming component-x.y.z folder with move fails occasionally

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#381]
Occasionally the renaming of "component-x.y.z" fails.
**This might be related to a "lock" during the unzip operation, 
caused by an AV scan directly after the extraction.**
The files are extracted, then the AV scan is running and locking the file, which we want to move.
So, the move fails silently.
All in all: i can not reproduce this issue - but users report it from time to time.

---
**Problem**
  - The installers use `move /Y "C:\server-web\bin\nginx-*" "c:\server-web-\bin\nginx\"`
  - Sometimes this doesn't work.
  - `/Y` - https://support.microsoft.com/en-us/kb/240268 - seems overwrite doesn't work for folders

**Todo**
- replace usage of "move" with "robocopy" to make it more robust
   - [x] Research: does this thingy support wildcards? 
    - we need to handle the following cases: `component-*`, where `*` is `master`, `githash` or `version`
    - Found out: **No**, Robocopy doesn't work with wildcards in the source folder name.
   - [ ] add retries with timer?
     - 1M retries (by default) with wait time 1 (/W:1)
   - [ ] add setup-rename.log

- resolve the wildcard before robocopy (pass full folder name to robocopy)
`rename.bat`
```
for /f "tokens=*" %%i in ('dir %1 /B') do 
robocopy "D:\server\bin\%%i" "D:\server\bin\%2" /MOVE /W:1 /S /MIR /MT:16
```` 
Usage: `rename component-* component`
