### ISSUE TITLE
v0.8.3 release issues

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#410]
**Round 1**
- [x] openssl missing in lite installers
- [ ] xdebug was not released yet for PHP7 (literc installers ship xdebug for 5.6)
    - **This needs a Note in the release text.**
- [x] conemu.7z not found
- [x] robomongo.zip not found
- [x] webinterface error #413 

Re-Released.

**Round 2**

- [ ] PHP extensions not downloaded = filesize 126byte = not extracted on install
  - [ ] Unable to load dynamic library 'ext\php_mongo.dll'
  - the PHP error causes all subsequent version grabs to fail:
     - [ ] webinterface php version switcher error - same as #411 
     - [x] SCP #411 & #412 
- [x] webinterface php extensions are listed, because echo left in
- [x] on install `phpext_ampq` - not copied `rabbitmq.1.dll` - #414 
- [x] phpext_zeromq - misses libzmq.dll, #415 

Re-Released.

**Round 3**

- [x] SCP PHP version not detected, #417 
- [x] php.ini 
   - [x] php_com_dotnet.dll not loaded by default
   - [x] openssl.cafile #416 
   - [x] `extension_dir` 

Re-Release in progress.. https://travis-ci.org/WPN-XM/WPN-XM/builds/68401621
Done.
