### ISSUE TITLE
redis configuration

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#424]
The component Redis will not run out of the box, because the official zip doesn't include a proper configuration file.

**Todo**
- [x] switch to releases from MSOpenTech (https://github.com/MSOpenTech/redis). 
      - because they provide a later version of Redis and a configuration file
      - [x] adjust crawler
      - [x] update registry
- [x] copy default config to `configs/redis`
- [x] tweak config so that Redis runs out of the box 
    - [x] `maxheap 4g`
    - [ ] `daemonize on` ???
       - On Windows, daemonize and pidfile are not supported.
    - [x] `logfile "../../logs/redis.log"`
- [x] integrate into installers

**Comment by TeroBlaZe** [comment]
maxheap 4g would create a 4g temp file each start and remove it each stop. It might cause some issues. I suggest to take a look at "maxmemory" flag

**Comment by jakoch** [comment]
Ok. Which values do you suggest?

**Comment by TeroBlaZe** [comment]
@jakoch I think maxmemory 64m is ok for development, and leave the maxheap off аs it will be set as 1.5 * maxmemory automatically

**Comment by jakoch** [comment]
Thank you for your suggestion.
Yes, the setting depends on the use case, but it makes sense to go with a low starting value as first basic out-of-the-box configuration.
