### ISSUE TITLE
add AB tool

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#467]
- add AB (apache benchmark) tool to the stack
  - to avoid discussions like #461 and base them on facts
- AB is included in the Apache releases, not distributed standalone (we can not crawl it)

**Todo**

- [x] repackage as standalone zip
  - `ab.zip` now available over at https://github.com/WPN-XM/benchmark-tools/releases/tag/v1.0
- [x] repackage for wpn-xm
   - [x] `/benchmark.bat` run several benchmarks and log results to log folder
   - [x] execute 3 test runs against an endpoint
   - [x] add endpoint (if users do not install webinterface)
      - [x] static html
      - [x] dynamic php
      - [x] static image
   - [ ] add nginx server block for endpoint to `domains-enabled`
      - not really needed
   - [x] package
      - https://github.com/WPN-XM/benchmark-tools/releases/download/v1.0/wpnxm-benchmark-1.0.0.zip
- [x] add to registry
- [x] add both zips to the download description file
- [ ] add to iss
  - [ ] full
  - [ ] standard
  - [ ] lite + literc
  - [ ] web
