### ISSUE TITLE
add roadmap and contributing documents, update developer docu

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#474]
The goal is to improve the project management and developer documentation.

- [x] add  `ROADMAP.md` document
  - describe the tasks and give them priorities
  - include existing issues from github
  - make it clear and transparent, where the project is heading

- [x] add `CONTRIBUTING.md` document  
    - explain steps on "how to contribute" to ease contribution

- [x] adjust `CHANGELOG.md`document to adhere to standards defined by http://keepachangelog.com/
