### ISSUE TITLE
[phpext_mongo] switch to phpext_mongodb

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#505]
pecl/mongodb is a new MongoDB driver for PHP, which will replace the legacy pecl/mongo driver.
- http://mongodb.github.io/mongo-php-driver/
- legacy: https://pecl.php.net/package/mongo
- new extension: https://pecl.php.net/package/mongodb

**Todo**
- [x] add crawler for phpext_mongodb
- [x] add to registry
- [x] adjust download description file 
- [x] adjust installers
- [x] adjust php configs
