### ISSUE TITLE
[updater] roadmap

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#515]
**Todo** 

**Downloading**

- [ ] **extend server-control-panel with an updater**
   - [ ] add button "updater" to main screen and to the tray
   - [ ] add update dialog
   - [ ] use table widget 
   - [ ] fetch registry as JSON via API
   - [ ] scan local installation folder and build "local repository of installed software" as JSON
   - [ ] compare versions - using json API against json "local repository" 
   - [ ] populate table accordingly
   - [ ] allow download of components 
       - [ ] add button "download"
       - [ ] if newer version is available, show update indication  
          - use a disabled green button 
    - [ ] after the download of a component
      - [ ] enable the "update" button, when the download arrived
      - [ ] change the "download" button to "install", when the download arrived
        - in other words: you can download multiple components in parallel 
        - and you trigger the update and install scripts individually afterwards
      - [ ] if new component, bind button to trigger the "install" script
      - [ ] if update component, bind button to trigger the "update" script
- [ ] **extend server-control-panel with a downloader**
   - [ ] add new class 
   - [ ] handle multiple requests
   - [ ] show progress for downloads
- [ ] **add "downloads in progress" lock file as a guard**
  - check for this file, before running update on the webinterface or the SCP
  - to prevent running update operations at the same time
  - set guard before download operation
     - [ ] from SCP
     - [ ] from webinterface
  - remove guard after download operation
     - [ ] from SCP
     - [ ] from webinterface
- [ ] **webinterface: drop the curl based downloader in the webinterface**
   - [ ] check, if we can integrate guzzle for parallel fetching
     - either in the webinterface or in the task-runner
   - [ ] else simply ship aria and use `aria -i downloads.txt`
     - check, if we can integrate aria into the task-runner (packaged phar)
- [ ] use `bin\downloads` as the target folder for downloads
  - we can't use temp, because the folder is under session auto-cleanup from the start cmd

**Installing and Updating**

- [ ] add install and update scripts
  - CLI scripts executed via the task-runner #471: `do update <component>` - `do install <component>`
  - we could extend or reuse functionality of the component classes from the webinterface
     - https://github.com/WPN-XM/webinterface/tree/master/php/Components
  - some of the install tasks can simply re-use the installation steps taken by the innosetup scripts
  - the update steps have to be written freshly
  - we probably need either "before" and "after" action event binding, to allow for instance "backup" to happen before updating or a state system with install steps
  - all install and update scripts are handled as individual issues

**Comment by klonos** [comment]
Might wanna add "stop service" step if component is running and then "start service" after installation/update is complete. Alternatively, force stop all services during update and start them all once done.

**Comment by jakoch** [comment]
Right! I totally forgot about that. Its pretty important, else the files in-use are blocked.

**Comment by jakoch** [comment]
I've news...

![updater](https://cloud.githubusercontent.com/assets/85608/13063615/38372b00-d44a-11e5-8bcc-1ab5259fe343.png)

- "Your Version" aka "current installed version" detection isn't working, yet. The task runner is need to grab the infos.
- Downloading and basic extraction of zip files works, but proper install tasks (post-install actions) are missing.
- I've prepared the tab for "PHP Software". That will be the PHP application gallery (#118). I've also added a new file to registry to contain the data. Maybe someone feels so inclined to help me a bit with the data. Thanks.

**Comment by klonos** [comment]
> I've news...

:tada: :clap: 

minor nit-picking: "Update starten.." ??? :smile: 

> - Maybe a contributor feels so inclined to help me a bit with the data: ...

What exactly do you need help with?

**Comment by klonos** [comment]
...filling in things like website and description for example? What is the timeframe/deadline here? I can allocate some time during the coming weekend perhaps, but I can only provide an updated file - don't know how to do PR. yet :disappointed:

**Comment by jakoch** [comment]
Hey Gregory :)

yes, a minor language issue.. consider it fixed.

Well, i need a bit of help to get data inserted into the PHP application registry.
Its a basic data entry task for the main keys like website, description, category, source-url.

(We can exclude the `versions` and `latest version` and `requirements` keys. These keys will be populated automatically. Versions/LatestVersion have to be crawled from the downloads pages to keep them up to date. Its to tedious to maintain this manually. And i hope that i can fetch the `requirements`, too. The idea is to use the `source-url` and read the data from the `composer.json` file.That should work for the majority of projects. Missing pieces needs to be filled manually.)

When you look at the array structure: is there a field missing which could be useful in the future?
 https://github.com/WPN-XM/registry/blob/master/wpnxm-php-software-registry.php#L19-L43

> What is the timeframe/deadline here? 

Take your time. There are no timeframe/deadlines on this project.

>   I can allocate some time during the coming weekend perhaps, but I can only provide an updated file - don't know how to do PR. yet :disappointed:

Oh.. didn't know that. 
Please don't use a summer weekend for boring stuff like this...

Editing a file and sending a PR is easy via the Github interface:

To edit:
Just browse/open the file and then click "edit the file". The icon is on the top right side. 
Github will fork the repository for you and then go into editor mode using this file.
When you are done editing, just enter a description for the commit and click "commit changes".
The changes will then live in your repository.

To send a PR:
Compare the changes to the original repository with "Compare and review" 
and then click "Create a Pull Request".
https://help.github.com/articles/using-pull-requests/#initiating-the-pull-request

**Comment by klonos** [comment]
Sounds pretty simple and I can follow well-laid out instructions. I will give this a go over the weekend then if time permits. Don't worry about it being summer and all. I am a workaholic and currently away from my wife and daughter. I usually have nothing to do during the nights besides wait for them to wake up so we can Skype (they are on the other hemisphere). This will give me a nice way to kill my time.

> When you look at the array structure: is there a field missing which could be useful in the future?

Did you know that Backdrop is my love when you linked to that specific part in the ```wpnxm-php-software-registry.php``` file or pure chance? :wink:

**Comment by jakoch** [comment]
If i remember correctly, you requested it some time ago. So, there we go..

**Comment by jakoch** [comment]
I'm stuck with this problem:

http://stackoverflow.com/questions/36721689/fetching-progress-signal-and-updating-multiple-progressbars

I'm stuck on the index problem for a while now. Thank you in advance for your help.

**Comment by jakoch** [comment]
Bounty: This question has an open bounty worth +200 reputation from me ending in 7 days on SO.

**Comment by jakoch** [comment]
Bounty was collected. Issue is fixed. 

![grr](http://i.stack.imgur.com/QuSJ3.gif)
