### ISSUE TITLE
reorganize the registry files

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#538]
Reorganize the registry repository

```
/installers/v0.8.5/standard-0.8.5-php5.6-w64.json
/installers/v0.8.6/standard-0.8.6-php5.6-w64.json
/installers/v[...]/[...].json
/installers/vNext/standard-next-php5.6-w64.json

LICENSE

wpnxm-php-software-registry.php
wpnxm-download-filenames.php
wpnxm-registry-metadata.php
wpnxm-software-registry.php
```

**Todo**
- [x] move all installer registries into versionized folders inside an "installers" folder
   - [x] the installer registries of the next version go into "installers/vNext"
- [x] add files `wpnxm-php-software-registry.php` including metadata, needed for #118 
- [x] add `wpnxm-registry-metadata.php`
- [x] move and rename `updater/data/downloadFilenames.php` to `registry/wpnxm-download-filenames.php`

**Follow-ups**
- [x] adjust "website/versionMatrix.php" to work with folder structure
- [x] adjust "website/downloads.php" to work with new folder structure
- [x] adjust Updater to work with the folder structure
- [x] adjust build scripts and updater to the new location and name of `downloadFilenames.php`
- [x] adjust build scripts to move the vNext files during rename into a versionized folder
