### ISSUE TITLE
add PHP extension SQLSRV

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#550]
**todo**
- research and testing needed to get this extension working out of the box
  - The releases are really odd. The extension zip has a non standard name and its hard to find the matching PHP version for the files.
- [x] license check
  - MIT
- [x] add version crawler for SQLSRV extension
  - https://github.com/Azure/msphpsql
- [x] add to registry
- [x] integrate into installers (only PHP7)
  - Note: files to copy `php_sqlsrv_7_nts.dll` & `php_pdo_sqlsrv_7_nts.dll`
  - [x] full
  - [x] standard
  - [x] web 
- [x] inform the user who asked for it over the forum (https://forum.wpn-xm.org/viewtopic.php?f=6&t=362)

----

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/32333653-add-php-extension-sqlsrv?utm_campaign=plugin&utm_content=tracker%2F164029&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F164029&utm_medium=issues&utm_source=github).

**Comment by jakoch** [comment]
On hold until the Azure guys fix issue 88 - `https://github.com/Azure/msphpsql/issues/88`

**Comment by jakoch** [comment]
added to registry
- https://github.com/WPN-XM/registry/commit/40bf2b186e1d73a42987dcbc2a1044717bd6fe1a
- https://github.com/WPN-XM/registry/commit/097ebe6a4c9133e18cd355b3b30c1f75cd2f30ef

**Comment by jakoch** [comment]
http://pecl.php.net/package/pdo_sqlsrv/4.1.6/windows

**Comment by jakoch** [comment]
Issue at sqlsrv is resolved by Microsoft, see https://github.com/Microsoft/msphpsql/issues/ 88 

- [ ] update crawlers to fetch extension from pecl
- [ ] update installers and remove old rename code (from the crappy old releases)
