### ISSUE TITLE
PHP CGI Spawner

### ISSUE THREAD

**Issue by adamdyson** [WPN-XM/WPN-XM#553]
I'm using the [php-cgi-spawner](https://github.com/deemru/php-cgi-spawner) in my batch files in order for PHP to handle more work that's being delegated from Nginx. I wasn't getting the expected results when using [run.bat](https://github.com/WPN-XM/WPN-XM/blob/master/startfiles/run.bat#L45) in conjunction with the default [nginx.conf](https://github.com/WPN-XM/software/blob/master/nginx/config/nginx.conf#L104), below are the changes I've made in order for Nginx to distribute the load across multiple PHP processes.

Firstly the `start-php` function was changed to:

```
:start-php
    echo Starting PHP FastCGI...

REM disable default FCGI request limit of 500
    set PHP_FCGI_MAX_REQUESTS=0
    set PHP_FCGI_CHILDREN=10

REM spawn multiple php processes at port 9100

    SET START_PORT=9100
    SET END_PORT=9119

    FOR /l %%p IN (%START_PORT%, 1, %END_PORT%) DO (
    %HIDECONSOLE% %~dp0bin\tools\spawn.exe %~dp0bin\php\php-cgi.exe %%p 1
    )

    echo.
goto END
```

The changes should be self explanatory, but I'm basically spawning 20 processes that listen on ports `9100` through to `9119`. Whereas as the default [run.bat](https://github.com/WPN-XM/WPN-XM/blob/master/startfiles/run.bat#L45) is spawning multiple processes which listens on the same port.

And the `php_pool` upstream was changed to:

```
upstream php_pool
{
    hash $request_uri consistent;

    server 127.0.0.1:9100 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9101 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9102 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9103 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9104 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9105 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9106 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9107 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9108 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9109 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9110 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9111 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9112 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9113 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9114 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9115 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9116 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9117 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9118 weight=1 max_fails=1 fail_timeout=1s;
    server 127.0.0.1:9119 weight=1 max_fails=1 fail_timeout=1s;
}
```

Obvious changes from the default [nginx.conf](https://github.com/WPN-XM/software/blob/master/nginx/config/nginx.conf#L104) is that there's more PHP processes handling work, but the important change was setting the load balancing method to [hash](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#hash).

Is there a better way and is it likely managing the PHP processes will be incorporated into the WPN-XM control panel?

**Comment by jakoch** [comment]
Hey Adam!

Thank you for bringing this up. Its an important feature of the next release. 
I've forked and added the spawner, because thestack still has the problem of crashing or blocking other requests.

> Is there a better way?

Your pool configuration is very good and solves both of these issues.
You have a port range with multiple instances and you are using the spawner for a single instance.
So, it's not only `php-cgi.exe -b <PORT> -c c:\server\bin\php\php.ini`, which wouldn't be crash safe.
And you .

Its hard to answer if there is a better way to configure the "load balancing". 
We would need to come up with some alternative configurations and measure and finally compare the results to draw a conclusion.

Nginx provides numerous ways to configure the balancing:
1. round-robin - default
2. `least_conn` - http://nginx.org/en/docs/http/ngx_http_upstream_module.html#least_conn
3. `ip_hash` - http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash
4. `hash key [consistent]` - http://nginx.org/en/docs/http/ngx_http_upstream_module.html#hash (ketama)

For instance, i've used `ip_hash` to allow session persistence (for login/re-login), but `hash key [consistent]` has probably the same effect, but uses a different algorithm in the background (libketama).

When you just want to spread load across your servers and the application has no demand for session consistency, then the default `round robin` is better and faster, because it doesn't spend time and resources on hashing a given key or client IP address.

> Is it likely managing the PHP processes will be incorporated into the WPN-XM control panel?

Yes. 

Please let us discuss what we need in the GUI.
I think the following three form elements should work out:
- Port: `9100` (as default)
- Number of PHP instances to start: `20` (maybe just 10 as default)
  - Each PHP instance will have its own port, starting from Port <9100>.
- Number of instances to spawn: `1` (as default)
  - Each PHP instance might be spawned multiple times, starting from <1>.

I'm open for suggestions. Best, Jens

**Comment by adamdyson** [comment]
> I've forked and added the spawner, because the stack still has the problem of crashing and blocking requests.

I developed an application recently (PHP 7.0.4) where I suffered the same problems. I'm not 100% certain, but it seemed like Nginx could not get a response from PHP unless the current process had finished or was terminated, I had no idea why because I'd never encountered this type of behaviour using Apache. To better explain, here's the basic workflow of the application.

```
// Entry point to the CRON schedule via command line where groups are
// executed asynchronously and tasks within a group are synchronous
php-cli index.php schedule:run
    |_ php-cli index.php shedule:run system
        |_ system:logRoate()
    |_ php-cli index.php shedule:run magento
        |_ magento:importItems()
        |_ magento:cancelItems()
    |_ php-cli index.php shedule:run fabricate
        |_ fabricate:renderArtwork()
```

The application (or stack) seemed to choke when the function `fabricate:renderArtwork()` was invoked, which under the hood uses Guzzle to concurrently download/generate PDF files from a controller action. The call stack looks something like.

```
Guzzle\Pool
    |_ Request(http://127.0.0.1/render/job/2342342
        |_ Controller:render()
            |_ $pdf = proc_open(electron.exe http://127.0.0.1/view/job/2342342)
    |_ Request(http://127.0.0.1/render/job/3453455
            |_ $pdf = proc_open(electron.exe http://127.0.0.1/view/job/3453455)
    |_ Request(http://127.0.0.1/render/job/7453451
            |_ $pdf = proc_open(electron.exe http://127.0.0.1/view/job/7453451)
    |_ Request(http://127.0.0.1/render/job/8345318
            |_ $pdf = proc_open(electron.exe http://127.0.0.1/view/job/8345318)
    |_ Request(http://127.0.0.1/render/job/9372277
            |_ $pdf = proc_open(electron.exe http://127.0.0.1/view/job/9372277)
```

So basically the `Controller:render()` action would get invoked, then within that function [Electron](http://electron.atom.io) would generate a PDF file from HTML, where the HTML is actually retrieved from the same Controller, `Controller:view()` action.

Before I made the change of spawning multiple PHP-CGI processes on different ports, the `Controller:view()` action would fail/timeout because the process that invoked the `Controller:render()` action was still running.

Also I discovered that using [ip_hash](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash) causes a similar lock-up issue for this type of application (because it calls itself) and the IP is always the same. Either it was an extreme oversight on my behalf or this needs to be documented somewhere!

> PHP itself will ship with spawning support starting with v7.1.

That's good to hear and I'm interested in finding out more about this, however I couldn't see any mention of it on [PHP RFC](https://wiki.php.net/rfc), where did you discover this?

> Please let us discuss what we need in the GUI.

To discuss the GUI requirements, I need to understand something first. The [php-cgi-spawner](https://github.com/deemru/php-cgi-spawner) supports 4 arguments.

```
spawner( char * app, unsigned port, unsigned cgis, unsigned restart_delay )
```

In what circumstance would you ever need more than 1 `cgis`. I don't really understand what the purpose would be to have multiple PHP-CGI processes listening on the same port? If Nginx forwarded simultaneous requests to port 9100 and there was 2 PHP-CGI processes listening, would both be used?

**Comment by jakoch** [comment]
Warning: tl:tr;

Thank you for the detailed issue description! Yes, thats the blocking problem. And all reports of  "the stack is slow" or "responses take over 3 seconds", "becomes unresponsive" boil down to this problem. 
Also with long running cURL requests: 
http://stackoverflow.com/questions/33024579/curl-does-not-work-from-php-on-nginx-and-localhost

>  I'd never encountered this type of behaviour using Apache

With Apache its either `CGI` or `mod_php` or `mod_fcgi`:
- The CGI approach means, that for every incoming request a new CGI process is spawned to process the request, just to shut down at the end of processing. This wastes a lot of resources and is slow.
- Then there is `mod_php`. This is probably the default way to combine PHP and Apache. Here the PHP interpreter is "embedded" inside the Apache process as "Module PHP". Based on the Apache config and especially your worker configuration, it will automatically spawn new workers/childs to process the incoming requests. Everything is nice under the umbrella of mod_php: Apache handles worker respawns and multiple requests. 
- Then there is FCGI.
The difference between Nginx and Apache is that `mod_fcgi` is again an Apache Module living inside the Apache process, while Nginx (with one or more childs) speaks to an external FCGI server (with one or more childs = php-cgi).
   - `request -> Nginx -> fastcgi_pass -> external FCGI (php-cgi)`

The interface is still CGI, but without the shutdown. The FCGI process stays - in listening mode.
  - The upside is that the response/request latency is lower that with CGI and that might lead to faster response times, because the "boottime" of CGI is gone and it consumes less resources.
  - But the downside is that it is only one process. When you have a long running request it will block, because there is no other slot for processing. 

> In what circumstance would you ever need more than 1 cgis. I don't really understand what the purpose would be to have multiple PHP-CGI processes listening on the same port? If Nginx forwarded simultaneous requests to port 9100 and there was 2 PHP-CGI processes listening, would both be used?

Its basically the constant `PHP_FCGI_CHILDREN`, which determines the number of processes spawned. This affects the number of PHP pages that can be processed at the same time.
Under the hood its either the master process listening and handing the work to one of its childs (one  listener) - or address reusage (multiple listeners).

The main problem is this isn't true on Windows. There is no re-spawning or multiplexing. Sentences like `luckily PHP5 will auto-spawn as many as you set in the PHP_FCGI_CHILDREN environment variable` do not hold. Referencing: https://www.nginx.com/resources/wiki/start/topics/examples/fastcgiexample/#spawning-a-fastcgi-process This is only true for Linux.

And this is where all the custom spawning solutions kick in to close the gap:
https://github.com/deemru/php-cgi-spawner#usage : `php-cgi-spawner.exe php/php-cgi.exe 9100 4`
(When using the php-cgi-spawner the maximum number of php-cgi processes is 64.)

I think of several child's on the same port as vertical scaling.

| Port   | 9100 | |
|--- |--- |--- |
|Child  | 1 | busy - long running curl |
|  | 2 | busy - long running pdf generation |
|  | 3 | waiting.. |
|  | 4 | wating.. |
|  | ... | |
| max.  | 64 |  |

Defining a port range is horizontal scaling.
If 9100 goes down or is already processing, Nginx would use the rest of the "pool" to "balance" and get the request processed (9101 or 9102 for the next request). How the work is spread across the pool is defined by the "load balancing" algo (see my other post). You could easily add another listener (on another box)  to the left or right by adding  ip:port to the pool. 

| Port   | 9100       | 9101     | 9102       | --> |
|---     |---         |---       |---         |---  |
|        |   1 (busy) | 1 (next) |  1 (next)  |     |

Well, then there are combinations of vertical and horizontal. 
But i'm not sure how these cases are handled. I assume horizontally, before vertically... but i don't want to spread false infos here. Its probably time to dig or ask for answers at StackOverflow ;) 

| Port   | 9100       | 9101  | 9102  | ... |
|---     |---         |---    |---    |---  |
| Child  |   1 (busy) | 1     |  1    |     |
|        |   2        | 2     |  2    |     |
|        |   3        | 3     |  3    |     |

------

Back to the Server Control Panel:

I think i split the php_pool / upstream configuration from the `nginx.conf` and into its own file `php_pool.conf`. This allows to write a new `php_pool.conf` from the SCP using a template approach - using the values from the dropdowns port and instances.

```
upstream php_pool
{
    hash $request_uri consistent;

    <servers>
}
```

```
<?php
$port = 9100;
$instances = 10;
$end_port = $port + ($instances-1);
$servers = '';

for($port; $port <= $end_port; $port++) {
    $servers .= 'server 127.0.0.1:'.$port.' weight=1 max_fails=1 fail_timeout=1s;' .PHP_EOL;
}
```

Ok, so much for now...

**Comment by adamdyson** [comment]
Hi @jakoch thanks for the schooling! I think I've finally had that light-bulb moment where it all makes sense now. Separating the upstream configuration from `nginx.conf` makes total sense and the example you posted for generating the `php_pool.conf` should be enough initially. Although I feel hard coding the upstream name `php_pool` and server address `127.0.0.1` could be limiting for some users.

I've always imagined the GUI looking something like this. Where any number of upstreams and servers can be created.

| Add Pool |
| --- |
---
| Name | Method|
| --- | --- |
| php_pool | $request_uri consistent |

| Add Server |
| --- |

| Address | Port | Weight | Max Fails | Fail Timeout | PHP Children |
| --- | --- | --- | --- | --- | --- |
| 192.168.0.10 | 9100 | 1 | 1 | 1s | 64 |
| 192.168.0.11 | 9101 | 1 | 1 | 1s | 64 |
| 192.168.0.12 | 9102 | 1 | 1 | 1s | 64 |
---

I'm not sure if the `wpn-xm.ini` file is the only way you persist data? But given the GUI above, it may be possible to output something like below. (Assuming that's how QT handles nested data).

```
[nginx]
config=./bin/nginx/conf/nginx.conf
sites=./www
port=80

[nginx/pools]

[nginx/pools/0]
name=php_pool
method=hash $request_uri consistent

[nginx/pools/0/servers]

[nginx/pools/0/servers/0]
address=192.168.0.10
port=9100
weight=1
maxfails=1
failtimeout=1s
phpchildren=64

[nginx/pools/0/servers/1]
address=192.168.0.11
port=9101
weight=1
maxfails=1
failtimeout=1s
phpchildren=64

[nginx/pools/0/servers/2]
address=192.168.0.12
port=9102
weight=1
maxfails=1
failtimeout=1s
phpchildren=64
```

Now with the nested data persisted, it should be pretty easy to dynamically generate the `php_pool.conf` as well as launch the number of `php-cgi.exe` processes needed, with a given `port` and `phpchildren`.

You're likely not going to be using PHP to handle this logic, but I figure if you can do it in PHP, you'll be able to convert it to C++.

```
$nginx = [
	'pools' => [
		0 => [
			'name' => 'php_pool',
			'method => 'hash $request_uri consistent'
			'servers' => [
				0 => [
					'address'=192.168.0.10,
					'port' => 9100,
					'weight' => 1,
					'maxfails' => 1,
					'failtimeout' => 1s,
					'phpchildren' => 64,
				],
				1 => [
					'address'=192.168.0.11,
					'port' => 9101,
					'weight' => 1,
					'maxfails' => 1,
					'failtimeout' => 1s,
					'phpchildren' => 64,
				],
				2 => [
					'address'=192.168.0.12,
					'port' => 9102,
					'weight' => 1,
					'maxfails' => 1,
					'failtimeout' => 1s,
					'phpchildren' => 64,
				],
			],
		],
	],
];

$config = '';
$commands = [];

foreach ($nginx['pools'] as $poolIndex => $poolData)
{
	$config .= sprintf('upstream %s {', $poolData['name']).PHP_EOL;
	$config .= sprintf('    %s', $poolData['name']).PHP_EOL;
	
	foreach ($poolData['servers'] as $serverIndex => $serverData)
	{
		$config .= sprintf('    server %s:%s weight=%s max_fails=%s fail_timeout=%s;',
			$serverData['address'],
			$serverData['port'],
			$serverData['weight'],
			$serverData['maxfails'],
			$serverData['failtimeout']
		).PHP_EOL;
		
		$commands[] = sprintf('%HIDECONSOLE% %~dp0bin\tools\spawn.exe %~dp0bin\php\php-cgi.exe %s %s',
			$serverData['port'],
			$serverData['phpchildren']
		);
	}
	
	$config .= sprintf('}').PHP_EOL;
}

foreach ($commands as $command)
{
	exec($command);
}
```

**Comment by jakoch** [comment]
Thank you so much for contributing. Its pretty rare, that i get good ideas with source-code attached as input or as the base for further discussion. 

> I've always imagined the GUI looking something like this. Where any number of upstreams and servers can be created.

I really like this GUI mockup. :+1: 

This requires a redesign of the current Configuration dialog. 
I need to introduce a stacked-widget (left) and sync it with a tab-widget (right).
The uses would select "Component > Nginx" in the stack, which opens the Tab "Upstream Configuration" to reach your GUI.

When there are multiple upstreams, we need a checkbox to select the active one.

> I'm not sure if the `wpn-xm.ini` file is the only way you persist data?

The SCP supports `ini` (for the settings file) and now also `json` (for registries).
I know, working with nested data in `ini` files is clumsy. We could use `json`. 

> Assuming that's how QT handles nested data

The example ini you posted should work.  A key like `nginx/pools/0/servers/2` is part of an array, http://doc.qt.io/qt-5.6/qsettings.html#beginWriteArray

> you'll be able to convert it to C++

The code is spot on and i'm able to convert it.

----

- [ ] redesign "Configuration" GUI
    - stacked widget (left-side)
    - tab widget (right-side)
    - sync
- [ ] GUI described above "Upstream Configuration"
      - QTableWidget  "Pool", "Servers"   
      - QPushButtons "Add Pool", "Add Server"
      - subdialogs for "Add Pool" and "Add Server"
        - "Ok" with SettingsManager::set() and "Cancel"
      - connections from buttons to subdialog
      - data for the table widgets comes from settings (in-memory)
        - SettingsManager::get()
      - hardcoded default config as fallback / initial config
      - "Reset to Default" button
- [ ] Servers::startPHP() needs a modification to spawn the php-cgi's (the exec command part)
- [ ] MainWindow, Column Port for PHP needs an indicator that a pool is active
    - maybe with a mouse-over text box showing the pool details (an ip+ports overview)

Lots of new ideas. Its less complicated than the updater, but still a lot of work.

**Comment by jakoch** [comment]
Update: i punched the new Config Dialog GUI out and created a Tab for the Upstream Config.

![upstream-config](https://cloud.githubusercontent.com/assets/85608/14781821/3c0afe6a-0ae5-11e6-9c67-462f83929778.png)

**Comment by adamdyson** [comment]
Wow Jens you knocked that up quick! I can't wait to start using it.

> Thank you so much for contributing. Its pretty rare, that i get good ideas with source-code attached as input or as the base for further discussion.

No problem at all. I'd like to contribute more on the coding side as well but its been a while since I dabbled in another language which wasn't web related. I might download QT and have a play around [537](https://github.com/WPN-XM/WPN-XM/issues/537), are you using the open source version?

> The SCP supports ini (for the settings file) and now also json (for registries).
> I know, working with nested data in ini files is clumsy. We could use json.

I was going to suggest using `json` but I didn't want to introduce another thing you'd have to develop into the control panel. Since you already support `json` for registry data, I'd definitely use it. It's going to be easier to work with and is consistent across other languages like `PHP` for example.

Keep up the good work.

**Comment by jakoch** [comment]
> Wow Jens you knocked that up quick! I can't wait to start using it.

Building GUI's is really easy with the Qt GUI designer. It's drag and drop.

> I might download QT and have a play around 537, are you using the open source version?

Sure. Give Qt a try. It's open-source and because the server-control-panel falls into the category "Open source distribution under a LGPL or GPL license" we can use it without paying a license fee. 
I've updated the download links: https://github.com/WPN-XM/server-control-panel#downloading-qt

> `json`: It's going to be easier to work with and is consistent across other languages like PHP for example.

Good point.

**Comment by jakoch** [comment]
Update: 
- i've added the dialogs AddPool and AddServer 
- they insert new rows into the tables
- in-table editing is possible, too
- content is written to `nginx-upstreams.json`

```
{
    "pools": {
        "0": {
            "method": "ip_hash",
            "name": "php_pool",
            "servers": {
                "0": {
                    "address": "localhost",
                    "failtimeout": "1s",
                    "maxfails": "1",
                    "phpchildren": "4",
                    "port": "9100",
                    "weight": "1"
                },
                "1": {
                    "address": "localhost",
                    "failtimeout": "1s",
                    "maxfails": "1",
                    "phpchildren": "6",
                    "port": "9101",
                    "weight": "1"
                },
                "2": {
                    "address": "localhost",
                    "failtimeout": "1s",
                    "maxfails": "1",
                    "phpchildren": "8",
                    "port": "9102",
                    "weight": "1"
                }
            }
        }
    }
}
```

- `json` file is the base for writing individual pool configs by "pool  name"
  - here `php_pool.conf` is created
- i've adjusted the `startPHP()` method to iterate over the servers of each pool and finally start PHP

```
[PHP] Not running... Skipping stop command.
[PHP] Set PHP_FCGI_MAX_REQUESTS "0" (disabled).
[PHP] Starting...
 "./bin/tools/spawn.exe ./bin/php/php-cgi.exe 9100 4"
[PHP] Starting...
 "./bin/tools/spawn.exe ./bin/php/php-cgi.exe 9101 6"
[PHP] Starting...
 "./bin/tools/spawn.exe ./bin/php/php-cgi.exe 9102 8"
```

In other words: we can now define servers in the "Nginx Upstream" pool and start them all easily and at once.

I hope its ok, that i implemented an "address" restriction on the `startPHP` method,
because we want to start local servers only - it will only take servers with address `localhost` or `127.0.0.1` into account. For starting a local server, we only need the "port" and the number of "PHP child" processes to spawn. Defining external server addresses is possible, but the user has to start (and take care) of them.

- [ ] missing: deleting rows and entries from the table
- [ ] json key sort order
     - working with QJsonObject and QJsonDocument doesn't guarantee the sort order of JSON keys
     - now its (in messy) alphabetical order
     - i guess i have to switch to a list of objects, instead of using a map.

So much for now... Jens

**Comment by adamdyson** [comment]
> Building GUI's is really easy with the Qt GUI designer. It's drag and drop.

I've been trying to learn more about QT and their editor in my spare time. I've come across mixed sources saying the QT plugin is not compatible with Visual Studio 2015? I'm aware of the [Qt5Package](https://visualstudiogallery.msdn.microsoft.com/c89ff880-8509-47a4-a262-e4fa07168408) but would prefer to use an official plugin if possible. Do you know if the [Version 1.2.5](http://download.qt.io/official_releases/vsaddin/qt-vs-addin-1.2.5.exe) works with VS2015?

> Update:

Everything you've done sounds great and should make for a solid stack. Let me know when you're able to push some code and I'll test it out.

> I ran into a problem with the example data we used. The addresses defined are in the local net (`192.168.0.10`) not on the localhost.

If I understand correctly, you can define non-local server addresses (`192.168.0.10`) and have them written to the `php_pool.conf` file, but the `startPHP()` method will ignore them when trying to spawn processes? That's completely fine, I personally have no need to run a cluster that way, well I do... but I'll always use Linux in production.

> working with QJsonObject and QJsonDocument doesn't guarantee the sort order of JSON keys

That's strange! Having the `json` structure you posted looks clean! While it might not be as easy to read using a list of objects, it's not going matter because having this new GUI should mean users will never have the need to read/edit the file manually ;)

**Comment by jakoch** [comment]
>  I've come across mixed sources saying the QT plugin is not compatible with Visual Studio 2015? I'm aware of the Qt5Package but would prefer to use an official plugin if possible. Do you know if the Version 1.2.5 works with VS2015?

No, sorry, i haven't tested the Qt plugins for Visual Studio, yet. 

I use `Qt mingw`+`Qt Creator` locally, 
because the [cross-compilation toolchain on Travis](https://github.com/WPN-XM/server-control-panel/blob/master/.travis.yml#L31-L32) is also based on `gcc + mingw`. 

> If I understand correctly, ... the startPHP() method will ignore them when trying to spawn processes? That's completely fine,...

Yes, correct. 
Ok.

> Having the json structure you posted looks clean!

I'd like to have the key "address" and "port" next to each other, but.. you are right!
It doesn't matter anymore, when the GUI is around.

> Let me know when you're able to push some code and I'll test it out.

This definitely needs testing. I've pushed the changes, 
but it needs one more round of cleanups and fixes to be ready for testing.

- [ ] pool configs should be written to `/bin/nginx/conf/upstream`
- [ ] auto-clear config files: before new configs are written, `del *.conf`` in `/bin/nginx/conf/upstream`
- [ ] `nginx-upstreams.json` should be written to a new folder `bin/wpnxm-scp`
- [ ] spawner support: with PHP7.1 `PHP_FCGI_CHILDREN` is supported and the spawner is not needed anymore. startPHP() needs to trigger a version detection: if below 7.1, use spawner, if 7.1+ drop spawner and (set environment var according to servers entry) use native PHP.

**Comment by jakoch** [comment]
Update: 

The change in FCGI handling on Windows is now official and ships with PHP 7.1:
Referencing:  https://github.com/php/php-src/blob/php-7.1.0alpha1/UPGRADING#L157

> PHP_FCGI_CHILDREN is respected. If this environment variable is defined,
> the first php-fcgi.exe process will exec the specified number of children.
> Those will share the same TCP socket.

**Todo**:
Problem: with PHP7.1 `PHP_FCGI_CHILDREN` is supported and the spawner is not needed anymore. This means we need a PHP version detection to determine, if we have to run use our Spawner or not.

- [ ] improve FCGI spawner support: 
   - [ ] startPHP() needs to trigger a version detection: 
   - if below `7.1`, use spawner, 
   - if `7.1+`
      - do not use our spawner
      - but set environment var `PHP_FCGI_CHILDREN` according to servers entry and use native PHP

**Comment by jakoch** [comment]
**Current Status**
- [ ] add "Reset to Default" buttons
- [ ] in the MainWindow the Column Port for PHP needs an indicator that a pool is active
     - it should show the details of the pool. so that the user has a an ip:ports + childs overview
      - maybe with a mouse-over text box showing the pool details

**Comment by deemru** [comment]
From the beggining of the year i started to use one new killer feature called `php-cgi` helpers, which now is available as part of [php-cgi-spawner (version 1.1)](https://github.com/deemru/php-cgi-spawner#version-11).

Shortly now you do not need to always keep permanently running `php-cgi` processes, you can use dynamically started `php-cgi` helpers, just use instead of `4` for example `1+128`, which means 1 permanent  `php-cgi` proccess (for opcache handling) plus up to 128 dynamic helpers.

Personally i thought `php-cgi-spawner` is reached EOL, but now it is debatable.

**Comment by jakoch** [comment]
Hello Dmitrii! 

Belated happy new year!

Thank you for posting the latest developments for the php-cgi-spawner. 
What can i say: **Awesome work**! 

The new feature enables users to work with one or more master processes and dynamically created childs based on `PHP_HELP_MAX_REQUESTS`.  When the master processes have opcode cache enabled, then the childs benefit from that, too. It reminds me of PHP-FPM's adaptive process spawning feature.
I also noticed that you worked on the `conhost`'s issue, because the process tree looks nice again.

With the latest features of the spawner, we can finally create a really stable and dynamic PHP backend using FCGI on Windows. And when combined with Nginx's load balancing feature, we get a really robust and reliable server environment. What a great start into 2017.

Regards, Jens

----

_Todo_
- [ ] update stack to the latest version of the spawner 
- [ ] add support for the new spawner feature to the server control panel
     - [ ] `9000 2+8` with `set PHP_HELP_MAX_REQUESTS` (port & static number of master processes + dynamic number of php childs based on max_requests)

**Comment by mindplay-dk** [comment]
@jakoch it's going on two years since the last release - looks like 0.8.7 is a bigger milestone that it sounds like... any chance of a pre/beta-release at some point? I need to do some benchmarking and only discovered last night that PHP scripts use only a single core at the moment...

**Comment by jakoch** [comment]
Hey Rasmus!

I'm sorry that it takes that long. This milestone is a walk through glue to me. Some of the features were (and are) complicated (for me) to implement, but i've [worked on a lot of issues for 0.8.7](https://github.com/WPN-XM/WPN-XM/issues?q=is%3Aissue+milestone%3Av0.8.7+is%3Aclosed). 

Because technical feedback is rare, it's not easy to come up with a good solutions all the time on the first take, so i have to go the extra mile and implement stuff multiple times to come up with a better solution. 
For instance, the new process monitoring required two rewrites before i was happy with it.

> any chance of a pre/beta-release at some point?

A new release is blocked by the unfinished work on the server control panel.
I don't want to disappoint users with the next release. So i can't give you an estimate.

In case you want to help, please fetch a CI build from Appveyor (https://ci.appveyor.com/api/buildjobs/077t4ns4p71k908n/artifacts/wpnxm-scp-dev-b5dff69-x64-msvc2015-boxed.zip). Please do some tests and provide some feedback. 
Warning included: PHP process start stop is currently in the making. Means process monitoring is there but no pool indication. 

> I need to do some benchmarking and only discovered last night that PHP scripts use only a single core at the moment...

:) Man, you are late to the bug party. 

It depends. On the PHP version and the execution context for the benchmark.
- The workaround for requests in the web context (nginx/php) is to create a upstream pool and use a newer PHP 7 version, which supports spawning childs out of the box.
- Then we have the spawner approach, which i'm still trying to get right (pool start, pool indication): this ticket. 
- Then we have PHP on the CLI, were multi-core is not really possible, unless i start to ship the thread-safe version of PHP. We could set the PHPTS version to the env path and spice it up with pthreads. That would give you multi-threading on the CLI. I haven't done this, because it doubles the amount of PHP versions to maintain.
- In regard to benchmarking: i've set up https://github.com/WPN-XM/benchmark-tools + https://github.com/WPN-XM/benchmark-tools/releases
This package ships with the stack by default (0.8.7 and up). Do you know any other good tool to include?

Regards, Jens

**Comment by jakoch** [comment]
**Current Status**
- [x] implemented a Tooltip to show PHP Ports and Childs (Column Port - MainWindow)
     - [ ] PHP needs an indicator that a pool is active
     - it should show the details of the pool. so that the user has a an ip:ports + childs overview
     - maybe with a mouse-over text box showing the pool details

Done.
