### ISSUE TITLE
Nginx build for Windows with ModSecurity

### ISSUE THREAD

**Issue by feb21** [WPN-XM/WPN-XM#557]
github **https://github.com/SpiderLabs/ModSecurity**

**Comment by jakoch** [comment]
Thank you for suggesting this feature.
I guess, you know what you are requesting, so for all others:

It would mean to compile Nginx with the module "modsecurity".

The problem is that this leads to a new standalone Nginx build project.
I would have to keep the original Nginx source in sync with the module(s) 
and compile, release and maintain this new custom Nginx build.
It also means to switch from official Nginx builds to our own builds for distribution.

I'm not against providing and maintaining such a build, but its simply more work.
And i have to be very careful where i spend my time on, because i'm already long overdue with a new release.

Maybe in the future...

**Comment by brainblowjob** [comment]
okay

**Comment by jakoch** [comment]
https://github.com/WPN-XM/nginx-windows

Goal is to a custom Nginx build with mod_security compiled in.

**Todo**
- [ ] appveyor.yml build script
- [ ] get
  - [ ] Nginx source
  - [ ] Nginx requirements
      - [ ] zlib
      - [ ] Perl
      - [ ] OpenSSL
   - [ ] third-party modules
     - [ ] ModSecurity source
- [ ] check, if Perl is present on Appveyor and which one. set PATH accordingly
- [ ] we need to find an easy way to allow upgrades to the third-party modules
- [ ] deploy to Github Releases

**Comment by jakoch** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=33926721)](https://www.bountysource.com/issues/33926721-nginx-build-for-windows-with-modsecurity?utm_source=33926721&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jakoch** [comment]
Seems it's not enough money to spawn interest or get a contribution.
Let's turn the problem:
How much money do you need to implement it?

**Comment by jakoch** [comment]
Nice to have, but nobody cares. Not even for money...
I might come back to this idea at a later point in time, though.
Thank you for the feature request and your support.
