### ISSUE TITLE
[scp] Desktop Popup Notification

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#559]
Qt has no popup desktop notification by default. For now we only have `tray->showMessage()`, which uses the Windows Notification system. But this is very limited and not very useful. 

For instance, i want to show some buttons and format the notification message as HTML.

As Qt is highly customizable and almost all widgets are inherited from QWidget, 
so a custom QWidget can be used as desktop popup. 
A QWidget is shown like any other top-level window. 
The following flags can be used to suppress the Dialog look and make it "appear" like a popup unlike general window.

```
setWindowFlags(
                Qt::Window | // Add if popup doesn't show up
                Qt::FramelessWindowHint | // No window border
                Qt::WindowDoesNotAcceptFocus | // No focus
                Qt::WindowStaysOnTopHint // Always on top
                );
```

To hide it from appearing in the task manager, call this function inside the constructor.

`setAttribute(Qt::WA_ShowWithoutActivating);`

----

**Todo**

- [ ] add Desktop Popup Notification
  - [ ] QWidget
  - [ ] setWindowFlags to make it appear as a popup and not as a dialog window
  - [ ] fadeIn / fadeOut - http://stackoverflow.com/a/32985126/1163786
