### ISSUE TITLE
[updater] setup cronjob to automate version crawling and registry updating

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#563]
The purpose is to have version crawling and updating of the registry fully automated.

**Todo**
- [ ] blocked by #562 (run crawler on CLI)
- [ ] setup cronjob 
   - [ ] to automate the version crawling
   - [ ] to commit the updated registries (if any)
