### ISSUE TITLE
Prepare Release v0.8.7

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#634]
#### Prepare Release v0.8.7
I have a lot of requests for the new version v0.8.7.
This issue is for keeping track of all the steps needed for preparing the next release.
I'm looking forward to get the new release out within the next two months.

But there are still a couple of issues to solve:
- most importantly the new process detection needs to be implemented
- the old webinterface needs to be excluded from shipping
- and sad, but true - the updater needs to be disabled, because the feature isn't ready without the scripts

#### Todo
- [ ] SCP with new process detection
- [ ] SCP with self-updater
- [ ] SCP with disabled component updater
- [ ] exclude webinterface from shipping (include a simple "It works!" page)
- [ ] check ISS scripts
- to be continued... i'm adding more tasks on the way
